# Generated by Django 4.1.1 on 2022-09-24 11:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='введите Ваш ник', max_length=20, unique=True, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Такой формат +79611234567', max_length=128, region=None, unique=True, verbose_name='номер')),
                ('email', models.EmailField(max_length=30, verbose_name='адрес эл почты')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'телефоны',
            },
        ),
    ]
