# Generated by Django 4.1.1 on 2022-09-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides_phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corse', models.CharField(choices=[('fi', 'Первый'), ('sc', 'Второй'), ('tr', 'Третий'), ('fo', 'Четвертый'), ('fv', 'Пятый')], default='fi', max_length=2, verbose_name='курс студента')),
                ('facultet', models.CharField(choices=[('ma', 'Математика'), ('li', 'Литература'), ('hi', 'История'), ('ph', 'Философия'), ('la', 'Лингвистика')], default='fi', max_length=2, verbose_name='факультет')),
                ('budjet', models.BooleanField(default=False, verbose_name='бюджетник?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_name', to='guides_phones.usersphone', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'список студентов',
            },
        ),
    ]
